name: Java Spring Boot with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build-test-package-spring-boot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        working-directory: ./attractions-service
        run: mvn -B package --file pom.xml